V1
106-inc/sim2022 pull request #33
Opened 2022-11-13 19:33 UTC by Tako-San

2022-11-13 20:48 UTC, derzhavin3016 requested changes

2022-11-13 20:48 UTC, derzhavin3016 commented on include/elfloader/elfloader.hh
> +  ELFIO::section *getSectionPtr(const std::string &name) const;
```suggestion
  const ELFIO::section *getSectionPtr(const std::string &name) const;
```

2022-11-13 20:48 UTC, derzhavin3016 commented on tools/simulator/main.cc
> +  app.add_option("input", input, "input")->required(); // input
I suppose you should provide more descriptive comments (or remove them) and more informative help string to option

2022-12-01 10:06 UTC, derzhavin3016 requested changes

2022-12-01 10:06 UTC, derzhavin3016 commented on src/decoder/decoder.py
> +    to_write += "inline std::unordered_map<OpType, std::string> opTypeToString {\n"
```suggestion
    to_write += "inline std::unordered_map<OpType, std::string_view> opTypeToString {\n"
```

2022-12-01 10:06 UTC, derzhavin3016 commented on src/decoder/decoder.py
> +    to_write += "#include <string>\n"
```suggestion
    to_write += "#include <string_view>\n"
```

2022-12-01 10:06 UTC, derzhavin3016 commented on include/common/inst.hh
> +    ss << std::setw(9) << opTypeToString[type] << " {";
I think you should consider using `at()` here
```suggestion
    ss << std::setw(9) << opTypeToString.at(type) << " {";
```

2022-12-01 10:06 UTC, derzhavin3016 commented on tools/simulator/main.cc
> +  std::map<std::string, lvl::level_enum> map{
```suggestion
  std::map<std::string_view, lvl::level_enum> map{
```

2022-12-01 10:18 UTC, Tako-San commented on tools/simulator/main.cc
> +  std::map<std::string, lvl::level_enum> map{
Doesn't work

2022-12-01 10:19 UTC, derzhavin3016 approved these changes
LGTMq+

2022-12-01 10:24 UTC, merged